name: Relatório de Bug
description: Registre um relatório de bug.
title: "[Bug]: "
labels: ["bug", "triagem"]
projects: ["octo-org/44"] # Substitua pelo projeto que deseja atrelar
assignees:
  - polvo-gato
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este relatório de bug!
  - type: input
    id: contato
    attributes:
      label: Detalhes de contato
      description: Como podemos entrar em contato com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: o-que-aconteceu
    attributes:
      label: O que aconteceu?
      description: Diga-nos também o que você esperava que acontecesse.
      placeholder: diga-nos o que você vê!
      value: "Ocorreu um bug!"
    validations:
      required: true
  - type: dropdown
    id: navegadores
    attributes:
      label: Em quais navegadores você está vendo o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Edge
        - Safari
        - Outros
  - type: textarea
    id: registros
    attributes:
      label: Saída de log relevante
      description: Copie e cole qualquer saída de log relevante. Ela será formatada automaticamente em código.
      render: shell
  # - type: checkboxes
  #   id: termos
  #   attributes:
  #     label: Código de Conduta
  #     description: Ao enviar este problema, você concorda em seguir nosso [Código de Conduta](https://example.com).
  #     options:
  #       - label: Concordo em seguir o Código de Conduta deste projeto
  #         required: true
