blank_issues_enabled: falso
links de contato:
  - nome: Suporte da Comunidade GitHub
    URL: https://github.com/orgs/community/discussions
    sobre: ​​Por favor, faça e responda perguntas aqui.
  - nome: GitHub Security Bug Bounty
    URL: https://bounty.github.com/
    sobre: ​​Por favor, reporte vulnerabilidades de segurança aqui.
