blank_issues_enabled: false
contact_links:
  - name: Suporte da Comunidade GitHub
    url: https://github.com/orgs/community/discussions
    about: Por favor, faça e responda perguntas aqui.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Por favor, reporte vulnerabilidades de segurança aqui.
