name: Add Issue to Project v2

on:
  issues:
    types: [labeled]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to Project Column
        uses: m7kvqbe1/github-action-move-issues@v1.0.0
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          project-url: "https://github.com/users/marcelomera/projects/2"
          target-labels: "Size: Small, Size: Medium"
          target-column: "Backlog"
          ignored-columns: "Ready, In Progress, In Review, Done"
