name: Add Issue to Project Todo Column

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
      PROJECT_OWNER: marcelomera
      PROJECT_NUMBER: 2 # Coloque o número do projeto correto
      STATUS_FIELD_NAME: Status
      TODO_OPTION_NAME: Backlog
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.SECRET_PAT }}" | gh auth login --with-token

      - name: Add issue to project and set status
        run: |
          ISSUE_URL=${{ github.event.issue.html_url }}

          # Get project ID
          PROJECT_ID=$(gh project view $PROJECT_NUMBER --owner "$PROJECT_OWNER" --format json | jq -r '.id')
          echo "Project ID: $PROJECT_ID"

          # Add issue to project
          ITEM_ID=$(gh project item-add --project-id "$PROJECT_ID" --url "$ISSUE_URL" --format json | jq -r '.id')
          echo "Item ID: $ITEM_ID"

          if [ -z "$ITEM_ID" ]; then
            echo "Failed to add issue to project."
            exit 1
          fi

          # Get Status field ID
          FIELDS=$(gh project field-list --project-id "$PROJECT_ID" --format json)
          STATUS_FIELD_ID=$(echo "$FIELDS" | jq -r --arg NAME "$STATUS_FIELD_NAME" '.fields[] | select(.name | ascii_downcase == ($NAME|ascii_downcase)) | .id')
          TODO_OPTION_ID=$(echo "$FIELDS" | jq -r --arg NAME "$TODO_OPTION_NAME" '.fields[] | select(.name | ascii_downcase == "status") | .options[] | select(.name | ascii_downcase == ($NAME|ascii_downcase)) | .id')

          if [ -z "$STATUS_FIELD_ID" ] || [ -z "$TODO_OPTION_ID" ]; then
            echo "Status field or Todo option not found."
            exit 1
          fi

          # Set the Status to Todo
          RESULT=$(gh project item-edit --id "$ITEM_ID" --project-id "$PROJECT_ID" --field-id "$STATUS_FIELD_ID" --single-select-option-id "$TODO_OPTION_ID" --format json)
          echo "Result: $RESULT"

          if echo "$RESULT" | jq -e '.id' > /dev/null; then
            echo "Issue added and set to Todo successfully."
          else
            echo "Error updating issue status."
            exit 1
          fi
