name: Add Issue to Project v2

on:
  issues:
    types: [opened] # dispara quando uma issue é criada

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Adicionar a issue ao Project v2
      - name: Add issue to Project v2
        uses: peter-evans/create-project-card@v2
        with:
          project-url: https://github.com/users/marcelomera/projects/2
          content-id: ${{ github.event.issue.node_id }}
          content-type: ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
