name: Adicionar Issues ao Project v2

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Adicionar issue ao Project v2
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/marcelomera/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
